/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;


class LibraryTest {
    Library sut = new Library();


    @Test
    public void testRollDice() {
        ArrayList<Integer> result = Library.roll(6);
        Assertions.assertEquals(6, result);
    }

    @Test
    public void testDuplicates() {
        int[] arr1 = {1,2,3,4,5,3,5,6};
        int[] arr2 = {1,2,3,4,5,6};
        boolean result1 = sut.containsDuplicates(arr1);
        boolean result2 = sut.containsDuplicates(arr2);

        Assertions.assertEquals(true,result1);
        Assertions.assertEquals(false,result2);
    }

    @Test
    public void testAverage() {
    int[] arr1 = {2,3,4,5,6,7} ;
    double result = sut.calculateAverage(arr1);
    Assertions.assertEquals(27, result);
    }

    @Test
    public void testArrayOfArrays() {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[] result = sut.arrayOfArrays(weeklyMonthTemperatures);
        Assertions.assertEquals(weeklyMonthTemperatures[2] ,result);
    }
}
