/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.ArrayList;
import java.util.Random;
import java.util.HashSet;



public class Library {
    public static ArrayList<Integer> roll(int n) {
        if (n <= 0) {
            return new ArrayList<>();
        }

        ArrayList<Integer> rolls = new ArrayList<>();
        Random random = new Random();

        for (int i = 0; i < n; i++) {
            int rollValue = random.nextInt(6) + 1;
            rolls.add(rollValue);
        }

        return rolls;
    }

    public static boolean containsDuplicates(int[] arr) {
        ArrayList<Integer> list = new ArrayList<>();
        for (int num : arr) {
            if (list.contains(num)) {
                return true;
            }
            list.add(num);
        }
        return false;
    }

    public static double calculateAverage(int[] arr) {
        if (arr == null) {
            return 0;
        }

        int sum = 0;
        for (int num : arr) {
            sum += num;
        }

        return (double) sum / arr.length ;
    }


    public static int[] arrayOfArrays(int[][] arrays) {
        if (arrays == null || arrays.length == 0) {
            return null;
        }

        int lowestAverage = Integer.MAX_VALUE;
        int lowestIndex = -1;

        for (int i = 0; i < arrays.length; i++) {
            int sum = 0;
            HashSet<Integer> uniqueValues = new HashSet<>();

            for (int num : arrays[i]) {
                sum += num;
                uniqueValues.add(num);
            }

            int average = sum / uniqueValues.size();
            if (average < lowestAverage) {
                lowestAverage = average;
                lowestIndex = i;
            }
        }

        return arrays[lowestIndex];
    }



//    public static void main(String[] args) {
//        int numRolls = 4;
//        ArrayList<Integer> result = roll(numRolls);
//        System.out.println(result);
//
//
//        int[][] weeklyMonthTemperatures = {
//                {66, 64, 58, 65, 71, 57, 60},
//                {57, 65, 65, 70, 72, 65, 51},
//                {55, 54, 60, 53, 59, 57, 61},
//                {65, 56, 55, 52, 55, 62, 57}
//        };
//
//        int[] coldestWeek = arrayOfArrays(weeklyMonthTemperatures);
//        System.out.print("Coldest week: ");
//        for (int temperature : coldestWeek) {
//            System.out.print(temperature + " ");
//        }
//
//    }



}
