/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;


public class App {
    public static List<String> lintJavaScriptFile(Path filePath) throws IOException {
        List<String> errorMessages = new ArrayList<>();
        List<String> lines = Files.readAllLines(filePath);

        for (int i = 0; i < lines.size(); i++) {
            String line = lines.get(i).trim();
            if (!line.isEmpty() &&
                    !line.endsWith("{") &&
                    !line.endsWith("}") &&
                    !line.contains("if") &&
                    !line.contains("else") &&
                    !line.endsWith(";")) {
                errorMessages.add("Line " + (i + 1) + ": Missing semicolon.");
            }
        }

        return errorMessages;
    }

    public static void main(String[] args) {
        Path filePath = Path.of("./app/src/main/resources/gates.js");
        try {
            List<String> errorMessages = lintJavaScriptFile(filePath);
            for (String errorMessage : errorMessages) {
                System.out.println(errorMessage);
            }
        } catch (IOException e) {
            System.out.println("Error reading the file: " + e.getMessage());
        }
    }
}
