/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;
import java.nio.file.Path;
import java.util.List;

class AppTest {
    @Test
    public void testNoErrors() throws Exception {
        Path filePath = Path.of("\\\\wsl$\\Ubuntu\\home\\aws\\java-fundamentals\\linter\\app\\src\\main\\resources\\gates.js");
        List<String> errorMessages = App.lintJavaScriptFile(filePath);
        assertEquals(0, errorMessages.size());
    }

    @Test
    public void testOneError() throws Exception {
        Path filePath = Path.of("\\\\wsl$\\Ubuntu\\home\\aws\\java-fundamentals\\linter\\app\\src\\main\\resources\\gates.js");
        List<String> errorMessages = App.lintJavaScriptFile(filePath);
        assertEquals(1, errorMessages.size());
        assertEquals("Line 1: Missing semicolon.", errorMessages.get(0));
    }

    @Test
    public void testFewErrors() throws Exception {
        Path filePath = Path.of("\\\\wsl$\\Ubuntu\\home\\aws\\java-fundamentals\\linter\\app\\src\\main\\resources\\gates.js");
        List<String> errorMessages = App.lintJavaScriptFile(filePath);
        assertEquals(2, errorMessages.size());
        assertEquals("Line 1: Missing semicolon.", errorMessages.get(0));
        assertEquals("Line 3: Missing semicolon.", errorMessages.get(1));
    }

    @Test
    public void testManyErrors() throws Exception {
        Path filePath = Path.of("\\\\wsl$\\Ubuntu\\home\\aws\\java-fundamentals\\linter\\app\\src\\main\\resources\\gates.js");
        List<String> errorMessages = App.lintJavaScriptFile(filePath);
        assertEquals(5, errorMessages.size());
    }

    @Test
    public void testEmptyFile() throws Exception {
        Path filePath = Path.of("\\\\wsl$\\Ubuntu\\home\\aws\\java-fundamentals\\linter\\app\\src\\main\\resources\\gates.js");
        List<String> errorMessages = App.lintJavaScriptFile(filePath);
        assertEquals(0, errorMessages.size());
    }
}
